version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/ccwebapp

    steps:
      # git pull
      - checkout
      - run:
          ame: Install packages
            command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Build Artifact
          command: |
                  cd webapp/csye6225_assignment1
                  pwd
                  ls -al
                  mvn clean install
                  ls -al

      - run:
          name: Decrpyt Secrets
          command: openssl enc -d -aes-256-ecb -md md5 -in src/main/resources/application-cloud.properties.secrets -out src/main/resources/application-cloud.properties -k $SECRETS_KEY

      # Download and cache dependencies
      - restore_cache:
          keys:
            - csye6225_assignment1-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: csye6225_assignment1-{{ checksum "pom.xml" }}



      # build and push docker image to docker hub
      - run: mvn clean compile jib:build -Dimage=zarinlo/ccwebapp:$CIRCLE_BUILD_NUM

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: ccwebapp
